spring:
   datasource:
      url: jdbc:mysql://localhost:3306/db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   batch:
      initialize-schema: ALWAYS
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true
      properties:
         hibernate:
            use_sql_comments: true